In [2]:
import pandas as pd

Explore 1st file in gene expression.

In [3]:
folder = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\gene expression"

df_1 = pd.read_csv(folder + r"\1_4_hpa_rna_celline.tsv", sep="\t")
print(df_1.shape)
print(df_1.head(100))

(24315372, 6)
               Gene Gene name Cell line   TPM  pTPM  nTPM
0   ENSG00000000003    TSPAN6      143B  22.0  27.6  25.9
1   ENSG00000000003    TSPAN6     22Rv1   2.8   3.6   2.7
2   ENSG00000000003    TSPAN6  23132/87   6.2   7.5   7.5
3   ENSG00000000003    TSPAN6      253J  14.2  18.7  25.4
4   ENSG00000000003    TSPAN6   253J-BV  13.0  17.1  18.5
..              ...       ...       ...   ...   ...   ...
95  ENSG00000000003    TSPAN6    CAL-27  12.2  14.9  16.0
96  ENSG00000000003    TSPAN6    CAL-29  20.1  25.0  29.0
97  ENSG00000000003    TSPAN6    CAL-33  13.4  18.1  18.5
98  ENSG00000000003    TSPAN6    CAL-51  41.3  54.3  39.1
99  ENSG00000000003    TSPAN6    CAL-54  13.1  17.1  15.9

[100 rows x 6 columns]

Explore 2nd file in gene expression.

In [4]:
df_2 = pd.read_csv(folder + r"\2_DepMap_OmicsExpressionAllGenesTPMLogp1Profile.csv")
print(df_2.shape)
print(df_2.head())

(1495, 53962)
  Unnamed: 0  TSPAN6 (ENSG00000000003)  TNMD (ENSG00000000005)  \
0  PR-AdBjpG                  4.331992                0.000000
1  PR-I2AzwG                  4.567424                0.584963
2  PR-5ekAAC                  3.150560                0.000000
3  PR-I21681                  5.085340                0.000000
4  PR-i9DRP1                  6.729417                0.000000

   DPM1 (ENSG00000000419)  SCYL3 (ENSG00000000457)  \
0                7.364660                 2.792855
1                7.106641                 2.543496
2                7.379118                 2.333424
3                7.154211                 2.545968
4                6.537917                 2.456806

   C1orf112 (ENSG00000000460)  FGR (ENSG00000000938)  CFH (ENSG00000000971)  \
0                    4.471187               0.028569               1.226509
1                    3.504620               0.000000               0.189034
2                    4.228049               0.056584               1.310340
3                    3.084064               0.000000               5.868390
4                    3.867896               0.799087               7.208478

   FUCA2 (ENSG00000001036)  GCLC (ENSG00000001084)  ...  ENSG00000288714  \
0                 3.044394                6.500005  ...         0.000000
1                 3.813525                4.221877  ...         0.000000
2                 6.687201                3.682573  ...         0.028569
3                 6.165309                4.489928  ...         0.000000
4                 5.570159                7.127117  ...         0.000000

   ENSG00000288717  ENSG00000288718  ENSG00000288719  ENSG00000288720  \
0         0.536053         0.000000         0.028569         0.176323
1         0.879706         0.000000         0.014355         0.014355
2         0.000000         0.084064         0.000000         0.097611
3         0.000000         0.070389         0.000000         0.176323
4         0.000000         0.201634         0.028569         0.137504

   ENSG00000288721  ENSG00000288722  ENSG00000288723  ENSG00000288724  \
0         0.992768         2.797013         0.000000              0.0
1         0.432959         2.972693         0.056584              0.0
2         0.367371         1.695994         0.084064              0.0
3         0.411426         3.921246         0.028569              0.0
4         0.678072         4.418190         0.000000              0.0

   ENSG00000288725
0         0.000000
1         0.070389
2         0.000000
3         0.000000
4         0.000000

[5 rows x 53962 columns]

In [5]:
print(df_2["Unnamed: 0"].head(20))

0     PR-AdBjpG
1     PR-I2AzwG
2     PR-5ekAAC
3     PR-I21681
4     PR-i9DRP1
5     PR-llpknG
6     PR-feSGd6
7     PR-z36vet
8     PR-7WaDe1
9     PR-DPUwIm
10    PR-O7UjdR
11    PR-I3QLzA
12    PR-yRj8KP
13    PR-0HHXsp
14    PR-r9EPko
15    PR-RMpAVe
16    PR-0hdbB5
17    PR-PEUSpj
18    PR-d95SZ5
19    PR-Koodhd
Name: Unnamed: 0, dtype: object

Explore 3rd file in gene expression.

In [6]:
df_3 = pd.read_csv(folder + r"\3_GEOexpression.txt", sep="\t")
print(df_3.shape)
print(df_3.head())

(19914, 3268)
              Gene    GSM101610    GSM101615    GSM101616    GSM101667  \
0  ENSG00000000003    33.615700   553.249756   540.452209   599.431152
1  ENSG00000000005    40.925682    31.327406    33.934967    34.213123
2  ENSG00000000419  2182.281250  3419.430420  3514.540039  2295.817383
3  ENSG00000000457    58.934814    95.068222    94.900459    51.810070
4  ENSG00000000460   136.418900   257.929169   271.317230   162.090073

     GSM101668    GSM101671    GSM101672    GSM101673    GSM101674  ...  \
0   625.242737   400.554657   412.995605   427.403900   461.123535  ...
1    32.466286    36.243233    37.952511    34.644428    34.225410  ...
2  2378.469727  2297.564697  2276.069092  2368.761475  2689.160156  ...
3    52.327530    50.011375    53.793667    51.172344    52.677490  ...
4   160.913849   206.788635   209.966019   134.272583   147.408554  ...

    GSM960289    GSM960290    GSM960291    GSM960292    GSM960293  \
0  197.712616   387.427826   116.657890   104.889442   158.400604
1    4.392303     4.230473     4.651096     5.175624     5.540960
2  936.201782  1162.099731  1249.029053  1354.346069  1159.747559
3   35.778347    57.736485    25.528204    24.593216    23.337006
4   14.693585    19.083935   114.056015   137.948593   149.641708

     GSM960294    GSM960295    GSM960296   GSM960297    GSM960298
0   736.519043   631.033142   791.054504  181.986893   353.206940
1     4.211264     4.159354     4.480873    4.630062     4.296047
2  1561.643799  1547.089233  1551.400146  939.964661  1054.350952
3    47.793488    41.268002    64.042831   37.363773    61.027988
4   111.793892    98.536613   167.151016   12.268769    24.296593

[5 rows x 3268 columns]

In [8]:
for gene in df_3["Gene"]:
    print(gene)

ENSG00000000003
ENSG00000000005
ENSG00000000419
ENSG00000000457
ENSG00000000460
ENSG00000000938
ENSG00000000971
ENSG00000001036
ENSG00000001084
ENSG00000001167
ENSG00000001460
ENSG00000001461
ENSG00000001497
ENSG00000001561
ENSG00000001617
ENSG00000001626
ENSG00000001629
ENSG00000002016
ENSG00000002079
ENSG00000002330
ENSG00000002549
ENSG00000002586
ENSG00000002587
ENSG00000002726
ENSG00000002745
ENSG00000002746
ENSG00000002834
ENSG00000002919
ENSG00000002933
ENSG00000003056
ENSG00000003096
ENSG00000003137
ENSG00000003147
ENSG00000003249
ENSG00000003393
ENSG00000003400
ENSG00000003402
ENSG00000003436
ENSG00000003509
ENSG00000003756
ENSG00000003987
ENSG00000003989
ENSG00000004059
ENSG00000004139
ENSG00000004142
ENSG00000004399
ENSG00000004455
ENSG00000004468
ENSG00000004478
ENSG00000004487
ENSG00000004534
ENSG00000004660
ENSG00000004700
ENSG00000004766
ENSG00000004776
ENSG00000004777
ENSG00000004779
ENSG00000004799
ENSG00000004809
ENSG00000004838
ENSG00000004846
ENSG00000004848
ENSG00000004864
ENSG00000004866
ENSG00000004897
ENSG00000004939
ENSG00000004948
ENSG00000004961
ENSG00000004975
ENSG00000005001
ENSG00000005007
ENSG00000005020
ENSG00000005022
ENSG00000005059
ENSG00000005073
ENSG00000005075
ENSG00000005102
ENSG00000005108
ENSG00000005156
ENSG00000005175
ENSG00000005187
ENSG00000005189
ENSG00000005194
ENSG00000005206
ENSG00000005238
ENSG00000005243
ENSG00000005249
ENSG00000005302
ENSG00000005339
ENSG00000005379
ENSG00000005381
ENSG00000005421
ENSG00000005436
ENSG00000005448
ENSG00000005469
ENSG00000005471
ENSG00000005483
ENSG00000005486
ENSG00000005513
ENSG00000005700
ENSG00000005801
ENSG00000005810
ENSG00000005812
ENSG00000005844
ENSG00000005882
ENSG00000005884
ENSG00000005889
ENSG00000005893
ENSG00000005961
ENSG00000005981
ENSG00000006007
ENSG00000006015
ENSG00000006016
ENSG00000006025
ENSG00000006042
ENSG00000006047
ENSG00000006062
ENSG00000006071
ENSG00000006116
ENSG00000006118
ENSG00000006128
ENSG00000006194
ENSG00000006210
ENSG00000006282
ENSG00000006283
ENSG00000006327
ENSG00000006377
ENSG00000006432
ENSG00000006451
ENSG00000006453
ENSG00000006459
ENSG00000006468
ENSG00000006530
ENSG00000006534
ENSG00000006555
ENSG00000006576
ENSG00000006606
ENSG00000006607
ENSG00000006611
ENSG00000006625
ENSG00000006634
ENSG00000006638
ENSG00000006659
ENSG00000006695
ENSG00000006704
ENSG00000006712
ENSG00000006715
ENSG00000006740
ENSG00000006744
ENSG00000006747
ENSG00000006756
ENSG00000006757
ENSG00000006788
ENSG00000006831
ENSG00000007001
ENSG00000007038
ENSG00000007047
ENSG00000007062
ENSG00000007080
ENSG00000007129
ENSG00000007168
ENSG00000007171
ENSG00000007174
ENSG00000007202
ENSG00000007216
ENSG00000007237
ENSG00000007255
ENSG00000007264
ENSG00000007306
ENSG00000007312
ENSG00000007314
ENSG00000007341
ENSG00000007350
ENSG00000007372
ENSG00000007376
ENSG00000007384
ENSG00000007392
ENSG00000007402
ENSG00000007516
ENSG00000007520
ENSG00000007541
ENSG00000007866
ENSG00000007908
ENSG00000007923
ENSG00000007933
ENSG00000007944
ENSG00000007952
ENSG00000007968
ENSG00000008018
ENSG00000008056
ENSG00000008083
ENSG00000008086
ENSG00000008118
ENSG00000008130
ENSG00000008196
ENSG00000008197
ENSG00000008226
ENSG00000008256
ENSG00000008277
ENSG00000008282
ENSG00000008283
ENSG00000008294
ENSG00000008300
ENSG00000008311
ENSG00000008323
ENSG00000008324
ENSG00000008382
ENSG00000008394
ENSG00000008405
ENSG00000008438
ENSG00000008441
ENSG00000008513
ENSG00000008516
ENSG00000008517
ENSG00000008710
ENSG00000008735
ENSG00000008838
ENSG00000008853
ENSG00000008869
ENSG00000008952
ENSG00000008988
ENSG00000009307
ENSG00000009335
ENSG00000009413
ENSG00000009694
ENSG00000009709
ENSG00000009724
ENSG00000009765
ENSG00000009780
ENSG00000009790
ENSG00000009830
ENSG00000009844
ENSG00000009950
ENSG00000009954
ENSG00000010017
ENSG00000010030
ENSG00000010072
ENSG00000010165
ENSG00000010244
ENSG00000010256
ENSG00000010270
ENSG00000010278
ENSG00000010292
ENSG00000010295
ENSG00000010310
ENSG00000010318
ENSG00000010319
ENSG00000010322
ENSG00000010327
ENSG00000010361
ENSG00000010379
ENSG00000010404
ENSG00000010438
ENSG00000010539
ENSG00000010610
ENSG00000010626
ENSG00000010671
ENSG00000010704
ENSG00000010803
ENSG00000010810
ENSG00000010818
ENSG00000010932
ENSG00000011007
ENSG00000011009
ENSG00000011021
ENSG00000011028
ENSG00000011083
ENSG00000011105
ENSG00000011114
ENSG00000011132
ENSG00000011143
ENSG00000011198
ENSG00000011201
ENSG00000011243
ENSG00000011258
ENSG00000011260
ENSG00000011275
ENSG00000011295
ENSG00000011304
ENSG00000011332
ENSG00000011347
ENSG00000011376
ENSG00000011405
ENSG00000011422
ENSG00000011426
ENSG00000011451
ENSG00000011454
ENSG00000011465
ENSG00000011478
ENSG00000011485
ENSG00000011523
ENSG00000011566
ENSG00000011590
ENSG00000011600
ENSG00000011638
ENSG00000011677
ENSG00000012048
ENSG00000012061
ENSG00000012124
ENSG00000012171
ENSG00000012174
ENSG00000012211
ENSG00000012223
ENSG00000012232
ENSG00000012504
ENSG00000012660
ENSG00000012779
ENSG00000012817
ENSG00000012822
ENSG00000012963
ENSG00000012983
ENSG00000013016
ENSG00000013275
ENSG00000013288
ENSG00000013293
ENSG00000013306
ENSG00000013364
ENSG00000013374
ENSG00000013375
ENSG00000013392
ENSG00000013441
ENSG00000013503
ENSG00000013523
ENSG00000013561
ENSG00000013563
ENSG00000013573
ENSG00000013583
ENSG00000013588
ENSG00000013619
ENSG00000013725
ENSG00000013810
ENSG00000014123
ENSG00000014164
ENSG00000014216
ENSG00000014257
ENSG00000014641
ENSG00000014824
ENSG00000014914
ENSG00000015133
ENSG00000015153
ENSG00000015171
ENSG00000015285
ENSG00000015413
ENSG00000015475
ENSG00000015520
ENSG00000015532
ENSG00000015592
ENSG00000015676
ENSG00000016082
ENSG00000016391
ENSG00000016402
ENSG00000016490
ENSG00000016602
ENSG00000016864
ENSG00000017260
ENSG00000017427
ENSG00000017483
ENSG00000017797
ENSG00000018189
ENSG00000018236
ENSG00000018280
ENSG00000018408
ENSG00000018510
ENSG00000018610
ENSG00000018625
ENSG00000018699
ENSG00000018869
ENSG00000019102
ENSG00000019144
ENSG00000019169
ENSG00000019186
ENSG00000019485
ENSG00000019505
ENSG00000019549
ENSG00000019582
ENSG00000019991
ENSG00000019995
ENSG00000020129
ENSG00000020181
ENSG00000020256
ENSG00000020577
ENSG00000020633
ENSG00000020922
ENSG00000021300
ENSG00000021355
ENSG00000021461
ENSG00000021488
ENSG00000021574
ENSG00000021645
ENSG00000021762
ENSG00000021776
ENSG00000021826
ENSG00000021852
ENSG00000022267
ENSG00000022277
ENSG00000022355
ENSG00000022556
ENSG00000022567
ENSG00000022840
ENSG00000022976
ENSG00000023041
ENSG00000023171
ENSG00000023191
ENSG00000023228
ENSG00000023287
ENSG00000023318
ENSG00000023330
ENSG00000023445
ENSG00000023516
ENSG00000023572
ENSG00000023608
ENSG00000023697
ENSG00000023734
ENSG00000023839
ENSG00000023892
ENSG00000023902
ENSG00000023909
ENSG00000024048
ENSG00000024422
ENSG00000024526
ENSG00000024862
ENSG00000025039
ENSG00000025156
ENSG00000025293
ENSG00000025423
ENSG00000025434
ENSG00000025708
ENSG00000025770
ENSG00000025772
ENSG00000025796
ENSG00000025800
ENSG00000026025
ENSG00000026103
ENSG00000026508
ENSG00000026559
ENSG00000026652
ENSG00000026751
ENSG00000026950
ENSG00000027001
ENSG00000027075
ENSG00000027644
ENSG00000027697
ENSG00000027847
ENSG00000027869
ENSG00000028116
ENSG00000028137
ENSG00000028203
ENSG00000028277
ENSG00000028310
ENSG00000028528
ENSG00000028839
ENSG00000029153
ENSG00000029363
ENSG00000029364
ENSG00000029534
ENSG00000029559
ENSG00000029639
ENSG00000029725
ENSG00000029993
ENSG00000030066
ENSG00000030304
ENSG00000030582
ENSG00000031003
ENSG00000031081
ENSG00000031691
ENSG00000031698
ENSG00000031823
ENSG00000032219
ENSG00000032389
ENSG00000032444
ENSG00000032742
ENSG00000033011
ENSG00000033030
ENSG00000033100
ENSG00000033122
ENSG00000033170
ENSG00000033178
ENSG00000033327
ENSG00000033627
ENSG00000033800
ENSG00000033867
ENSG00000034053
ENSG00000034152
ENSG00000034239
ENSG00000034510
ENSG00000034533
ENSG00000034677
ENSG00000034693
ENSG00000034713
ENSG00000034971
ENSG00000035115
ENSG00000035141
ENSG00000035403
ENSG00000035499
ENSG00000035664
ENSG00000035681
ENSG00000035687
ENSG00000035720
ENSG00000035862
ENSG00000035928
ENSG00000036054
ENSG00000036257
ENSG00000036448
ENSG00000036530
ENSG00000036549
ENSG00000036565
ENSG00000036672
ENSG00000036828
ENSG00000037042
ENSG00000037280
ENSG00000037474
ENSG00000037637
ENSG00000037749
ENSG00000037757
ENSG00000037897
ENSG00000038002
ENSG00000038210
ENSG00000038219
ENSG00000038274
ENSG00000038295
ENSG00000038382
ENSG00000038427
ENSG00000038532
ENSG00000038945
ENSG00000039068
ENSG00000039123
ENSG00000039139
ENSG00000039319
ENSG00000039523
ENSG00000039537
ENSG00000039560
ENSG00000039600
ENSG00000039650
ENSG00000039987
ENSG00000040199
ENSG00000040275
ENSG00000040341
ENSG00000040487
ENSG00000040531
ENSG00000040608
ENSG00000040633
ENSG00000040731
ENSG00000040933
ENSG00000041353
ENSG00000041357
ENSG00000041515
ENSG00000041802
ENSG00000041880
ENSG00000041982
ENSG00000041988
ENSG00000042062
ENSG00000042088
ENSG00000042286
ENSG00000042304
ENSG00000042317
ENSG00000042429
ENSG00000042445
ENSG00000042493
ENSG00000042753
ENSG00000042781
ENSG00000042813
ENSG00000042832
ENSG00000042980
ENSG00000043039
ENSG00000043093
ENSG00000043143
ENSG00000043355
ENSG00000043462
ENSG00000043514
ENSG00000043591
ENSG00000044012
ENSG00000044090
ENSG00000044115
ENSG00000044446
ENSG00000044459
ENSG00000044524
ENSG00000044574
ENSG00000046604
ENSG00000046647
ENSG00000046651
ENSG00000046653
ENSG00000046774
ENSG00000046889
ENSG00000047056
ENSG00000047188
ENSG00000047230
ENSG00000047249
ENSG00000047315
ENSG00000047346
ENSG00000047365
ENSG00000047410
ENSG00000047457
ENSG00000047578
ENSG00000047579
ENSG00000047617
ENSG00000047621
ENSG00000047634
ENSG00000047644
ENSG00000047648
ENSG00000047662
ENSG00000047849
ENSG00000047932
ENSG00000047936
ENSG00000048028
ENSG00000048052
ENSG00000048140
ENSG00000048162
ENSG00000048342
ENSG00000048392
ENSG00000048405
ENSG00000048462
ENSG00000048471
ENSG00000048540
ENSG00000048544
ENSG00000048649
ENSG00000048707
ENSG00000048740
ENSG00000048828
ENSG00000048991
ENSG00000049089
ENSG00000049130
ENSG00000049167
ENSG00000049192
ENSG00000049239
ENSG00000049245
ENSG00000049246
ENSG00000049247
ENSG00000049249
ENSG00000049283
ENSG00000049323
ENSG00000049540
ENSG00000049541
ENSG00000049618
ENSG00000049656
ENSG00000049759
ENSG00000049768
ENSG00000049769
ENSG00000049860
ENSG00000049883
ENSG00000050030
ENSG00000050130
ENSG00000050165
ENSG00000050327
ENSG00000050344
ENSG00000050393
ENSG00000050405
ENSG00000050426
ENSG00000050438
ENSG00000050555
ENSG00000050628
ENSG00000050730
ENSG00000050748
ENSG00000050767
ENSG00000050820
ENSG00000051009
ENSG00000051108
ENSG00000051128
ENSG00000051180
ENSG00000051341
ENSG00000051382
ENSG00000051523
ENSG00000051620
ENSG00000051825
ENSG00000052126
ENSG00000052344
ENSG00000052723
ENSG00000052749
ENSG00000052795
ENSG00000052802
ENSG00000052841
ENSG00000052850
ENSG00000053108
ENSG00000053254
ENSG00000053371
ENSG00000053372
ENSG00000053438
ENSG00000053501
ENSG00000053524
ENSG00000053702
ENSG00000053747
ENSG00000053770
ENSG00000053900
ENSG00000053918
ENSG00000054116
ENSG00000054118
ENSG00000054148
ENSG00000054179
ENSG00000054267
ENSG00000054277
ENSG00000054282
ENSG00000054356
ENSG00000054392
ENSG00000054523
ENSG00000054598
ENSG00000054611
ENSG00000054654
ENSG00000054690
ENSG00000054793
ENSG00000054796
ENSG00000054803
ENSG00000054938
ENSG00000054965
ENSG00000054967
ENSG00000054983
ENSG00000055044
ENSG00000055070
ENSG00000055118
ENSG00000055130
ENSG00000055147
ENSG00000055163
ENSG00000055208
ENSG00000055211
ENSG00000055332
ENSG00000055483
ENSG00000055609
ENSG00000055732
ENSG00000055917
ENSG00000055950
ENSG00000055955
ENSG00000055957
ENSG00000056050
ENSG00000056097
ENSG00000056277
ENSG00000056291
ENSG00000056487
ENSG00000056558
ENSG00000056586
ENSG00000056736
ENSG00000056972
ENSG00000056998
ENSG00000057019
ENSG00000057149
ENSG00000057252
ENSG00000057294
ENSG00000057468
ENSG00000057593
ENSG00000057608
ENSG00000057657
ENSG00000057663
ENSG00000057704
ENSG00000057757
ENSG00000057935
ENSG00000058056
ENSG00000058063
ENSG00000058085
ENSG00000058091
ENSG00000058262
ENSG00000058272
ENSG00000058335
ENSG00000058404
ENSG00000058453
ENSG00000058600
ENSG00000058668
ENSG00000058729
ENSG00000058799
ENSG00000058804
ENSG00000058866
ENSG00000059122
ENSG00000059145
ENSG00000059377
ENSG00000059378
ENSG00000059573
ENSG00000059588
ENSG00000059691
ENSG00000059728
ENSG00000059758
ENSG00000059804
ENSG00000059915
ENSG00000060069
ENSG00000060138
ENSG00000060140
ENSG00000060237
ENSG00000060303
ENSG00000060339
ENSG00000060491
ENSG00000060558
ENSG00000060566
ENSG00000060642
ENSG00000060656
ENSG00000060688
ENSG00000060709
ENSG00000060718
ENSG00000060749
ENSG00000060762
ENSG00000060971
ENSG00000060982
ENSG00000061273
ENSG00000061337
ENSG00000061455
ENSG00000061492
ENSG00000061656
ENSG00000061676
ENSG00000061794
ENSG00000061918
ENSG00000061936
ENSG00000061938
ENSG00000061987
ENSG00000062038
ENSG00000062096
ENSG00000062194
ENSG00000062282
ENSG00000062370
ENSG00000062524
ENSG00000062598
ENSG00000062650
ENSG00000062716
ENSG00000062725
ENSG00000063015
ENSG00000063127
ENSG00000063176
ENSG00000063177
ENSG00000063180
ENSG00000063241
ENSG00000063244
ENSG00000063245
ENSG00000063322
ENSG00000063515
ENSG00000063587
ENSG00000063601
ENSG00000063660
ENSG00000063761
ENSG00000063854
ENSG00000063978
ENSG00000064012
ENSG00000064042
ENSG00000064102
ENSG00000064115
ENSG00000064195
ENSG00000064199
ENSG00000064201
ENSG00000064205
ENSG00000064218
ENSG00000064225
ENSG00000064270
ENSG00000064300
ENSG00000064309
ENSG00000064313
ENSG00000064393
ENSG00000064419
ENSG00000064490
ENSG00000064545
ENSG00000064547
ENSG00000064601
ENSG00000064607
ENSG00000064651
ENSG00000064652
ENSG00000064655
ENSG00000064666
ENSG00000064687
ENSG00000064692
ENSG00000064703
ENSG00000064726
ENSG00000064763
ENSG00000064787
ENSG00000064835
ENSG00000064886
ENSG00000064932
ENSG00000064933
ENSG00000064961
ENSG00000064989
ENSG00000064995
ENSG00000064999
ENSG00000065000
ENSG00000065029
ENSG00000065054
ENSG00000065057
ENSG00000065060
ENSG00000065135
ENSG00000065150
ENSG00000065154
ENSG00000065183
ENSG00000065243
ENSG00000065268
ENSG00000065308
ENSG00000065320
ENSG00000065325
ENSG00000065328
ENSG00000065357
ENSG00000065361
ENSG00000065371
ENSG00000065413
ENSG00000065427
ENSG00000065485
ENSG00000065491
ENSG00000065518
ENSG00000065526
ENSG00000065534
ENSG00000065548
ENSG00000065559
ENSG00000065600
ENSG00000065609
ENSG00000065613
ENSG00000065615
ENSG00000065618
ENSG00000065621
ENSG00000065665
ENSG00000065675
ENSG00000065717
ENSG00000065802
ENSG00000065809
ENSG00000065833
ENSG00000065882
ENSG00000065883
ENSG00000065911
ENSG00000065923
ENSG00000065970
ENSG00000065989
ENSG00000066027
ENSG00000066032
ENSG00000066044
ENSG00000066056
ENSG00000066084
ENSG00000066117
ENSG00000066136
ENSG00000066185
ENSG00000066230
ENSG00000066248
ENSG00000066279
ENSG00000066294
ENSG00000066322
ENSG00000066336
ENSG00000066379
ENSG00000066382
ENSG00000066405
ENSG00000066422
ENSG00000066427
ENSG00000066455
ENSG00000066468
ENSG00000066557
ENSG00000066583
ENSG00000066629
ENSG00000066651
ENSG00000066654
ENSG00000066735
ENSG00000066739
ENSG00000066777
ENSG00000066827
ENSG00000066855
ENSG00000066923
ENSG00000066926
ENSG00000066933
ENSG00000067048
ENSG00000067057
ENSG00000067064
ENSG00000067066
ENSG00000067082
ENSG00000067113
ENSG00000067141
ENSG00000067167
ENSG00000067177
ENSG00000067182
ENSG00000067191
ENSG00000067208
ENSG00000067221
ENSG00000067225
ENSG00000067248
ENSG00000067334
ENSG00000067365
ENSG00000067369
ENSG00000067445
ENSG00000067533
ENSG00000067560
ENSG00000067596
ENSG00000067606
ENSG00000067646
ENSG00000067704
ENSG00000067715
ENSG00000067798
ENSG00000067829
ENSG00000067840
ENSG00000067842
ENSG00000067900
ENSG00000067955
ENSG00000067992
ENSG00000068001
ENSG00000068024
ENSG00000068028
ENSG00000068078
ENSG00000068079
ENSG00000068097
ENSG00000068120
ENSG00000068137
ENSG00000068305
ENSG00000068308
ENSG00000068323
ENSG00000068354
ENSG00000068383
ENSG00000068394
ENSG00000068400
ENSG00000068438
ENSG00000068615
ENSG00000068650
ENSG00000068654
ENSG00000068697
ENSG00000068724
ENSG00000068745
ENSG00000068784
ENSG00000068831
ENSG00000068878
ENSG00000068903
ENSG00000068912
ENSG00000068971
ENSG00000068976
ENSG00000068985
ENSG00000069011
ENSG00000069018
ENSG00000069020
ENSG00000069122
ENSG00000069188
ENSG00000069206
ENSG00000069248
ENSG00000069275
ENSG00000069329
ENSG00000069345
ENSG00000069399
ENSG00000069424
ENSG00000069431
ENSG00000069482
ENSG00000069493
ENSG00000069509
ENSG00000069535
ENSG00000069667
ENSG00000069696
ENSG00000069702
ENSG00000069764
ENSG00000069812
ENSG00000069849
ENSG00000069869
ENSG00000069943
ENSG00000069956
ENSG00000069966
ENSG00000069974
ENSG00000069998
ENSG00000070010
ENSG00000070018
ENSG00000070019
ENSG00000070031
ENSG00000070047
ENSG00000070061
ENSG00000070081
ENSG00000070159
ENSG00000070182
ENSG00000070190
ENSG00000070193
ENSG00000070214
ENSG00000070269
ENSG00000070366
ENSG00000070367
ENSG00000070371
ENSG00000070388
ENSG00000070404
ENSG00000070413
ENSG00000070423
ENSG00000070444
ENSG00000070476
ENSG00000070495
ENSG00000070501
ENSG00000070526
ENSG00000070540
ENSG00000070601
ENSG00000070610
ENSG00000070614
ENSG00000070718
ENSG00000070729
ENSG00000070748
ENSG00000070756
ENSG00000070761
ENSG00000070770
ENSG00000070778
ENSG00000070785
ENSG00000070808
ENSG00000070814
ENSG00000070831
ENSG00000070882
ENSG00000070886
ENSG00000070915
ENSG00000070950
ENSG00000070961
ENSG00000070985
ENSG00000071051
ENSG00000071054
ENSG00000071073
ENSG00000071082
ENSG00000071127
ENSG00000071189
ENSG00000071203
ENSG00000071205
ENSG00000071242
ENSG00000071243
ENSG00000071246
ENSG00000071282
ENSG00000071462
ENSG00000071537
ENSG00000071539
ENSG00000071553
ENSG00000071564
ENSG00000071575
ENSG00000071626
ENSG00000071655
ENSG00000071677
ENSG00000071794
ENSG00000071859
ENSG00000071889
ENSG00000071894
ENSG00000071909
ENSG00000071967
ENSG00000071991
ENSG00000071994
ENSG00000072041
ENSG00000072062
ENSG00000072071
ENSG00000072080
ENSG00000072110
ENSG00000072121
ENSG00000072133
ENSG00000072134
ENSG00000072135
ENSG00000072163
ENSG00000072182
ENSG00000072195
ENSG00000072201
ENSG00000072210
ENSG00000072274
ENSG00000072310
ENSG00000072315
ENSG00000072364
ENSG00000072401
ENSG00000072415
ENSG00000072422
ENSG00000072501
ENSG00000072506
ENSG00000072518
ENSG00000072571
ENSG00000072609
ENSG00000072657
ENSG00000072682
ENSG00000072694
ENSG00000072736
ENSG00000072756
ENSG00000072778
ENSG00000072786
ENSG00000072803
ENSG00000072818
ENSG00000072832
ENSG00000072840
ENSG00000072849
ENSG00000072858
ENSG00000072864
ENSG00000072954
ENSG00000072958
ENSG00000073008
ENSG00000073050
ENSG00000073060
ENSG00000073067
ENSG00000073111
ENSG00000073146
ENSG00000073150
ENSG00000073169
ENSG00000073282
ENSG00000073331
ENSG00000073350
ENSG00000073417
ENSG00000073464
ENSG00000073536
ENSG00000073584
ENSG00000073598
ENSG00000073605
ENSG00000073614
ENSG00000073670
ENSG00000073711
ENSG00000073712
ENSG00000073734
ENSG00000073737
ENSG00000073754
ENSG00000073756
ENSG00000073792
ENSG00000073803
ENSG00000073849
ENSG00000073861
ENSG00000073910
ENSG00000073921
ENSG00000073969
ENSG00000074047
ENSG00000074054
ENSG00000074071
ENSG00000074181
ENSG00000074201
ENSG00000074211
ENSG00000074219
ENSG00000074266
ENSG00000074276
ENSG00000074317
ENSG00000074319
ENSG00000074356
ENSG00000074370
ENSG00000074410
ENSG00000074416
ENSG00000074527
ENSG00000074582
ENSG00000074590
ENSG00000074603
ENSG00000074621
ENSG00000074660
ENSG00000074695
ENSG00000074696
ENSG00000074706
ENSG00000074755
ENSG00000074771
ENSG00000074800
ENSG00000074803
ENSG00000074842
ENSG00000074855
ENSG00000074935
ENSG00000074964
ENSG00000074966
ENSG00000075035
ENSG00000075043
ENSG00000075073
ENSG00000075089
ENSG00000075131
ENSG00000075142
ENSG00000075151
ENSG00000075188
ENSG00000075213
ENSG00000075218
ENSG00000075223
ENSG00000075234
ENSG00000075239
ENSG00000075240
ENSG00000075275
ENSG00000075290
ENSG00000075292
ENSG00000075303
ENSG00000075336
ENSG00000075340
ENSG00000075388
ENSG00000075391
ENSG00000075399
ENSG00000075413
ENSG00000075415
ENSG00000075420
ENSG00000075426
ENSG00000075429
ENSG00000075461
ENSG00000075539
ENSG00000075568
ENSG00000075618
ENSG00000075643
ENSG00000075651
ENSG00000075673

Explore 4th file in gene expression.

In [17]:
df_4 = pd.read_csv(folder + r"\4_Harmonized_MS_CCLE_Gygi_subsetted.csv")
print(df_4.shape)
print(df_4.head())

(375, 12559)
   Unnamed: 0  A0AV96 (RBM47)  A0AVF1 (IFT56)  A0AVG3 (TSNARE1)  \
0  ACH-000849        0.358567       -0.172066               NaN
1  ACH-000441       -1.112410        0.339446               NaN
2  ACH-000248        0.855575       -0.181171               NaN
3  ACH-000684        0.061377       -0.341233               NaN
4  ACH-000856        0.284258       -0.059558               NaN

   A0AVI4 (TMEM129)  A0AVK6 (E2F8)  A0AVT1 (UBA6)  A0JLT2 (MED19)  \
0               NaN            NaN      -0.496842        0.267691
1               NaN            NaN      -0.395633       -0.262715
2               NaN            NaN      -0.284720       -0.436849
3               NaN            NaN       1.481536       -0.006424
4               NaN            NaN      -0.520511        0.680164

   A0JNW5 (BLTP3B)  A0MZ66 (SHTN1)  ...  Q9Y6N7-2 (ROBO1)  Q9Y4E1-4 (WASHC2C)  \
0         0.045754        0.065342  ...          0.255903           -0.081142
1        -0.414909       -0.396370  ...          0.199431           -0.300508
2         0.555351        1.550787  ...         -0.849680            0.096941
3         0.185271       -0.125160  ...         -0.230147            0.148388
4        -0.281309       -0.691303  ...         -0.024407            0.698199

   Q9Y6Q5-2 (AP1M2)  Q9Y6K9-2 (IKBKG)  Q9Y3Y2-3 (CHTOP)  Q9Y4P1-2 (ATG4B)  \
0          1.680544          0.001122          0.684397          0.397332
1         -0.414740          0.178375         -0.387377         -0.008456
2          1.120568         -0.512328          0.102240         -0.204140
3         -0.162396          0.279161         -0.057371         -0.331465
4         -0.518353         -0.292139          0.498029          0.283140

   Q9Y6I3-1 (EPN1)  Q9Y5V3-2 (MAGED1)  Q9Y575-3 (ASB3)  Q9Y2L9-2 (LRCH1)
0         0.209930          -0.197547              NaN         -1.100381
1        -0.482339           0.148685              NaN          0.484499
2         0.039421          -0.761104              NaN         -1.191209
3        -0.014308           0.617058              NaN          0.409230
4        -0.123974          -0.560028              NaN         -0.120029

[5 rows x 12559 columns]

In [10]:
gene_prop = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\gene properties"

df_6 = pd.read_csv(gene_prop + r"\6_OmicsSomaticMutationsProfile.csv")
print(df_6.shape)
print(df_6.head())
print(df_6.columns.tolist())

C:\Users\Pattanun\AppData\Local\Temp\ipykernel_6796\2509133369.py:3: DtypeWarning: Columns (22,50,54,56,57,58,59,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df_6 = pd.read_csv(gene_prop + r"\6_OmicsSomaticMutationsProfile.csv")

(1066869, 70)
  Chrom     Pos Ref Alt     AF  DP  RefCount  AltCount   GT        PS  ...  \
0  chr1  818203   G   A  0.240  27        21         6  0/1       NaN  ...
1  chr1  851926   G   A  0.158  17        15         2  0/1       NaN  ...
2  chr1  924510  GC  AA  0.412  35        21        14  0|1  924510.0  ...
3  chr1  924657   C   G  0.437  17         9         8  0/1       NaN  ...
4  chr1  924750   C   T  0.625  19         7        12  0/1       NaN  ...

  GwasPmID GtexGene ProveanPrediction AMClass AMPathogenicity Rescue  \
0      NaN      NaN               NaN     NaN             NaN  False
1      NaN      NaN               NaN     NaN             NaN  False
2      NaN      NaN               NaN     NaN             NaN  False
3      NaN      NaN               NaN     NaN             NaN  False
4      NaN      NaN               NaN     NaN             NaN  False

  RescueReason  ProfileID Hotspot EntrezGeneID
0          NaN  PR-t8SaQo   False     400728.0
1          NaN  PR-lhMBt6   False     643837.0
2          NaN  PR-uKiczK   False     148398.0
3          NaN  PR-sxFiuq   False     148398.0
4          NaN  PR-DNEoiz   False     148398.0

[5 rows x 70 columns]
['Chrom', 'Pos', 'Ref', 'Alt', 'AF', 'DP', 'RefCount', 'AltCount', 'GT', 'PS', 'VariantType', 'VariantInfo', 'DNAChange', 'ProteinChange', 'HugoSymbol', 'Exon', 'Intron', 'EnsemblGeneID', 'EnsemblFeatureID', 'HgncName', 'HgncFamily', 'UniprotID', 'DbsnpRsID', 'GcContent', 'LofGeneName', 'LofGeneId', 'LofNumberOfTranscriptsInGene', 'LofPercentOfTranscriptsAffected', 'NMD', 'MolecularConsequence', 'VepImpact', 'VepBiotype', 'VepHgncID', 'VepExistingVariation', 'VepManeSelect', 'VepENSP', 'VepSwissprot', 'Sift', 'Polyphen', 'GnomadeAF', 'GnomadgAF', 'VepClinSig', 'VepSomatic', 'VepPliGeneValue', 'VepLofTool', 'OncogeneHighImpact', 'TumorSuppressorHighImpact', 'TranscriptLikelyLof', 'Brca1FuncScore', 'CivicID', 'CivicDescription', 'CivicScore', 'LikelyLoF', 'HessDriver', 'HessSignature', 'RevelScore', 'PharmgkbId', 'DidaID', 'DidaName', 'GwasDisease', 'GwasPmID', 'GtexGene', 'ProveanPrediction', 'AMClass', 'AMPathogenicity', 'Rescue', 'RescueReason', 'ProfileID', 'Hotspot', 'EntrezGeneID']

### Nomenclature

In [18]:
nom_folder = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\nomenclature"
print(os.listdir(nom_folder))

['10_GEOInfo.txt', '11_hpa_rna_celline_description.tsv', '7_cellosaurus.csv', '8_DepMap_OmicsProfiles.csv', '9_DepMap_sample_info.csv']

explore HPA to look up the name to cellosaurus

In [19]:
nom_folder = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\nomenclature"

df_7 = pd.read_csv(nom_folder + r"\7_cellosaurus.csv")
print(df_7.shape)
print(df_7.head())
print(df_7.columns.tolist())

(152231, 17)
  Identifier (cell line name) Accession (CVCL_xxxx)  \
0            #132 PC3-1-SC-E8             CVCL_B0T9
1             #132 PL12 SC-D1             CVCL_B0T8
2                   #15310-LN             CVCL_E548
3                      #16-15             CVCL_KA96
4                        #40a             CVCL_IW91

  Secondary accession number(s)  \
0                           NaN
1                           NaN
2                           NaN
3                           NaN
4                           NaN

                                            Synonyms  \
0                                         Z48-5MG-70
1                                         Z48-5MG-63
2  15310-LN; TER461; TER-461; Ter 461; TER479; TE...
3                                                NaN
4                                                NaN

                                    Cross-references References identifiers  \
0                               Wikidata; Q108819335    Patent=EP0501779A1;
1                               Wikidata; Q108819336    Patent=EP0501779A1;
2  dbMHC; 48439 || ECACC; 94050311 || IHW; IHW093...                    NaN
3                RCB; RCB4635 || Wikidata; Q54422067       PubMed=25400923;
4                                Wikidata; Q54422071       PubMed=28159921;

                                           Web pages  \
0                                                NaN
1                                                NaN
2  http://pathology.ucla.edu/workfiles/360cx.pdf ...
3                                                NaN
4                                                NaN

                                            Comments STR profile data  \
0  Group: Patented cell line. || Registration: In...              NaN
1  Group: Patented cell line. || Registration: In...              NaN
2  Part of: 12th International Histocompatibility...              NaN
3  Monoclonal antibody isotype: IgM. || Monoclona...              NaN
4  Characteristics: Established from parent cell ...              NaN

                           Diseases  \
0                               NaN
1                               NaN
2                               NaN
3                               NaN
4  NCIt; C21619; Mouse mesothelioma

                                   Species of origin  \
0           NCBI_TaxID=10090; ! Mus musculus (Mouse)
1           NCBI_TaxID=10090; ! Mus musculus (Mouse)
2            NCBI_TaxID=9606; ! Homo sapiens (Human)
3  NCBI_TaxID=10090; ! Mus musculus (Mouse) || NC...
4           NCBI_TaxID=10090; ! Mus musculus (Mouse)

                               Hierarchy Originate from same individual  \
0  CVCL_D145 ! HL-1 Friendly Myeloma-653                            NaN
1  CVCL_D145 ! HL-1 Friendly Myeloma-653                            NaN
2                                    NaN                            NaN
3               CVCL_4032 ! P3X63Ag8.653                            NaN
4                         CVCL_IW90 ! 40                            NaN

  Sex of cell Age of donor at sampling               Category  \
0         NaN                      NaN              Hybridoma
1         NaN                      NaN              Hybridoma
2      Female          Age unspecified  Transformed cell line
3         NaN                      NaN              Hybridoma
4        Male                     1-2M       Cancer cell line

                                Date (entry history)
0  Created: 23-09-21; Last updated: 30-01-24; Ver...
1  Created: 23-09-21; Last updated: 30-01-24; Ver...
2  Created: 22-10-12; Last updated: 30-01-24; Ver...
3  Created: 22-08-17; Last updated: 21-03-23; Ver...
4  Created: 15-05-17; Last updated: 29-06-23; Ver...
['Identifier (cell line name)', 'Accession (CVCL_xxxx)', 'Secondary accession number(s)', 'Synonyms', 'Cross-references', 'References identifiers', 'Web pages', 'Comments', 'STR profile data', 'Diseases', 'Species of origin', 'Hierarchy', 'Originate from same individual', 'Sex of cell', 'Age of donor at sampling', 'Category', 'Date (entry history)']

In [22]:
print(df_7[["Identifier (cell line name)", "Accession (CVCL_xxxx)", "Synonyms"]].head(10))

  Identifier (cell line name) Accession (CVCL_xxxx)  \
0            #132 PC3-1-SC-E8             CVCL_B0T9
1             #132 PL12 SC-D1             CVCL_B0T8
2                   #15310-LN             CVCL_E548
3                      #16-15             CVCL_KA96
4                        #40a             CVCL_IW91
5                        #490             CVCL_B375
6                        #822             CVCL_X345
7                       #G65G             CVCL_C4ZN
8                      #W7079             CVCL_E549
9                (BF1) 8A3.31             CVCL_G217

                                            Synonyms
0                                         Z48-5MG-70
1                                         Z48-5MG-63
2  15310-LN; TER461; TER-461; Ter 461; TER479; TE...
3                                                NaN
4                                                NaN
5                                   490; Mab 7; Mab7
6                                 822; Mab 13; Mab13
7                                                NaN
8                           #W7079 REM; REMUS; W7079
9                                                NaN

explore omic profile

In [23]:
df_8 = pd.read_csv(nom_folder + r"\8_DepMap_OmicsProfiles.csv")
print(df_8.shape)
print(df_8.head())
print(df_8.columns.tolist())

(3830, 5)
   ProfileID  ModelCondition     ModelID Datatype WESKit
0  PR-00UtU3  MC-001131-kkJv  ACH-001131      wgs    NaN
1  PR-01r7OM  MC-000957-Yckn  ACH-000957      rna    NaN
2  PR-02XmLG  MC-002785-qo9e  ACH-002785      rna    NaN
3  PR-04VvBz  MC-001289-BpdI  ACH-001289      wes    ICE
4  PR-09gmEI  MC-000520-YIm7  ACH-000520      rna    NaN
['ProfileID', 'ModelCondition', 'ModelID', 'Datatype', 'WESKit']

explore file 9

In [24]:
df_9 = pd.read_csv(nom_folder + r"\9_DepMap_sample_info.csv")
print(df_9.shape)
print(df_9.head())
print(df_9.columns.tolist())

(1840, 29)
    DepMap_ID cell_line_name stripped_cell_line_name  \
0  ACH-000016         SLR 21                   SLR21
1  ACH-000032     MHH-CALL-3                MHHCALL3
2  ACH-000033      NCI-H1819                NCIH1819
3  ACH-000043       Hs 895.T                  HS895T
4  ACH-000049         HEK TE                   HEKTE

                                     CCLE_Name alias  COSMICID     sex  \
0                                 SLR21_KIDNEY   NaN       NaN     NaN
1  MHHCALL3_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE   NaN       NaN  Female
2                                NCIH1819_LUNG   NaN       NaN  Female
3                            HS895T_FIBROBLAST   NaN       NaN  Female
4                                 HEKTE_KIDNEY   NaN       NaN     NaN

         source       RRID  WTSI_Master_Cell_ID  ...   lineage_sub_subtype  \
0  Academic lab  CVCL_V607                  NaN  ...                   NaN
1          DSMZ  CVCL_0089                  NaN  ...                b_cell
2  Academic lab  CVCL_1497                  NaN  ...  NSCLC_adenocarcinoma
3          ATCC  CVCL_0993                  NaN  ...                   NaN
4  Academic lab  CVCL_WS59                  NaN  ...                   NaN

  lineage_molecular_subtype default_growth_pattern model_manipulation  \
0                       NaN                    NaN                NaN
1                       NaN                    NaN                NaN
2                       NaN                    NaN                NaN
3                       NaN           2D: adherent                NaN
4                       NaN                    NaN       immortalized

  model_manipulation_details patient_id parent_depmap_id  \
0                        NaN  PT-JnARLB              NaN
1                        NaN  PT-p2KOyI              NaN
2                        NaN  PT-9p1WQv              NaN
3                        NaN  PT-rTUVZQ              NaN
4                        NaN  PT-qWYYgr              NaN

                   Cellosaurus_NCIt_disease Cellosaurus_NCIt_id  \
0           Clear cell renal cell carcinoma               C4033
1  Childhood B acute lymphoblastic leukemia               C9140
2                       Lung adenocarcinoma               C3512
3                                  Melanoma               C3224
4                                       NaN                 NaN

                                  Cellosaurus_issues
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4  No information is available about this cell li...

[5 rows x 29 columns]
['DepMap_ID', 'cell_line_name', 'stripped_cell_line_name', 'CCLE_Name', 'alias', 'COSMICID', 'sex', 'source', 'RRID', 'WTSI_Master_Cell_ID', 'sample_collection_site', 'primary_or_metastasis', 'primary_disease', 'Subtype', 'age', 'Sanger_Model_ID', 'depmap_public_comments', 'lineage', 'lineage_subtype', 'lineage_sub_subtype', 'lineage_molecular_subtype', 'default_growth_pattern', 'model_manipulation', 'model_manipulation_details', 'patient_id', 'parent_depmap_id', 'Cellosaurus_NCIt_disease', 'Cellosaurus_NCIt_id', 'Cellosaurus_issues']

explore file 10 especially for GEO

In [25]:
df_10 = pd.read_csv(nom_folder + r"\10_GEOInfo.txt", sep="\t")
print(df_10.shape)
print(df_10.head())
print(df_10.columns.tolist())

(3267, 23)
  Geo_accession CEL_file_names title status submission_date last_update_date  \
0     GSM101610      GSM101610   NaN    NaN             NaN              NaN
1     GSM101615      GSM101615   NaN    NaN             NaN              NaN
2     GSM101616      GSM101616   NaN    NaN             NaN              NaN
3     GSM101667      GSM101667   NaN    NaN             NaN              NaN
4     GSM101668      GSM101668   NaN    NaN             NaN              NaN

  type  channel_count source_name_ch1 organism_ch1  ... contact_institute  \
0  NaN            NaN             NaN          NaN  ...               NaN
1  NaN            NaN             NaN          NaN  ...               NaN
2  NaN            NaN             NaN          NaN  ...               NaN
3  NaN            NaN             NaN          NaN  ...               NaN
4  NaN            NaN             NaN          NaN  ...               NaN

  GSE_ID GSE_filename cell_line disease origin Cellosaurus_ID Cellline  \
0    NaN          NaN       NaN     NaN    NaN      CVCL_0131    A-172
1    NaN          NaN       NaN     NaN    NaN      CVCL_0393   LN-229
2    NaN          NaN       NaN     NaN    NaN      CVCL_0393   LN-229
3    NaN          NaN       NaN     NaN    NaN      CVCL_1715   SW1088
4    NaN          NaN       NaN     NaN    NaN      CVCL_1715   SW1088

   Matching_Type cell_line_Trimmed
0  Cello GEO GSM               NaN
1  Cello GEO GSM               NaN
2  Cello GEO GSM               NaN
3  Cello GEO GSM               NaN
4  Cello GEO GSM               NaN

[5 rows x 23 columns]
['Geo_accession', 'CEL_file_names', 'title', 'status', 'submission_date', 'last_update_date', 'type', 'channel_count', 'source_name_ch1', 'organism_ch1', 'characteristics_ch1', 'platform_id', 'contact_country', 'contact_institute', 'GSE_ID', 'GSE_filename', 'cell_line', 'disease', 'origin', 'Cellosaurus_ID', 'Cellline', 'Matching_Type', 'cell_line_Trimmed']

explore file 11 especially for HPA

In [26]:
df_11 = pd.read_csv(nom_folder + r"\11_hpa_rna_celline_description.tsv", sep="\t")
print(df_11.shape)
print(df_11.head())
print(df_11.columns.tolist())

(1206, 7)
  Cell line          Disease Disease subtype Cellosaurus ID   Patient  \
0      143B      Bone cancer    Osteosarcoma      CVCL_2270        13
1     22Rv1  Prostate cancer  Adenocarcinoma      CVCL_1045      Male
2  23132/87   Gastric cancer  Adenocarcinoma      CVCL_1046  Male, 72
3      253J   Bladder cancer       Carcinoma      CVCL_7935  Male, 53
4   253J-BV   Bladder cancer       Carcinoma      CVCL_7937  Male, 53

  Primary/Metastasis Sample collection site
0            Primary                   bone
1            primary               prostate
2            primary                stomach
3         metastasis             lymph node
4         metastasis             lymph node
['Cell line', 'Disease', 'Disease subtype', 'Cellosaurus ID', 'Patient', 'Primary/Metastasis', 'Sample collection site']

### Non gene expression

In [27]:
import os

gene_prop = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\gene properties"
non_gene = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\non gene expression"

print("gene properties:")
print(os.listdir(gene_prop))

print("\nnon gene expression:")
print(os.listdir(non_gene))

gene properties:
['5_OmicsFusionFilteredSupplementary.csv', '6_OmicsSomaticMutationsProfile.csv']

non gene expression:
['12_CCLE_metabolomics_20190502.csv', '13_CCLE_miRNA_20181103.gct', '14_OmicsGlobalSignatures.csv']

### Fact_proteomics

In [4]:
import pandas as pd

folder = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\gene expression"
df_4 = pd.read_csv(folder + r"\4_Harmonized_MS_CCLE_Gygi_subsetted.csv")
print(df_4.shape)
print(df_4.head())
print(df_4.columns[:10].tolist())

(375, 12559)
   Unnamed: 0  A0AV96 (RBM47)  A0AVF1 (IFT56)  A0AVG3 (TSNARE1)  \
0  ACH-000849        0.358567       -0.172066               NaN
1  ACH-000441       -1.112410        0.339446               NaN
2  ACH-000248        0.855575       -0.181171               NaN
3  ACH-000684        0.061377       -0.341233               NaN
4  ACH-000856        0.284258       -0.059558               NaN

   A0AVI4 (TMEM129)  A0AVK6 (E2F8)  A0AVT1 (UBA6)  A0JLT2 (MED19)  \
0               NaN            NaN      -0.496842        0.267691
1               NaN            NaN      -0.395633       -0.262715
2               NaN            NaN      -0.284720       -0.436849
3               NaN            NaN       1.481536       -0.006424
4               NaN            NaN      -0.520511        0.680164

   A0JNW5 (BLTP3B)  A0MZ66 (SHTN1)  ...  Q9Y6N7-2 (ROBO1)  Q9Y4E1-4 (WASHC2C)  \
0         0.045754        0.065342  ...          0.255903           -0.081142
1        -0.414909       -0.396370  ...          0.199431           -0.300508
2         0.555351        1.550787  ...         -0.849680            0.096941
3         0.185271       -0.125160  ...         -0.230147            0.148388
4        -0.281309       -0.691303  ...         -0.024407            0.698199

   Q9Y6Q5-2 (AP1M2)  Q9Y6K9-2 (IKBKG)  Q9Y3Y2-3 (CHTOP)  Q9Y4P1-2 (ATG4B)  \
0          1.680544          0.001122          0.684397          0.397332
1         -0.414740          0.178375         -0.387377         -0.008456
2          1.120568         -0.512328          0.102240         -0.204140
3         -0.162396          0.279161         -0.057371         -0.331465
4         -0.518353         -0.292139          0.498029          0.283140

   Q9Y6I3-1 (EPN1)  Q9Y5V3-2 (MAGED1)  Q9Y575-3 (ASB3)  Q9Y2L9-2 (LRCH1)
0         0.209930          -0.197547              NaN         -1.100381
1        -0.482339           0.148685              NaN          0.484499
2         0.039421          -0.761104              NaN         -1.191209
3        -0.014308           0.617058              NaN          0.409230
4        -0.123974          -0.560028              NaN         -0.120029

[5 rows x 12559 columns]
['Unnamed: 0', 'A0AV96 (RBM47)', 'A0AVF1 (IFT56)', 'A0AVG3 (TSNARE1)', 'A0AVI4 (TMEM129)', 'A0AVK6 (E2F8)', 'A0AVT1 (UBA6)', 'A0JLT2 (MED19)', 'A0JNW5 (BLTP3B)', 'A0MZ66 (SHTN1)']

In [5]:
df_4 = df_4.rename(columns={"Unnamed: 0": "ACH_ID"})

In [6]:
df_4_long = df_4.melt(
    id_vars=["ACH_ID"],
    var_name="protein_col",
    value_name="protein_intensity"
)
print(df_4_long.shape)
print(df_4_long.head())

(4709250, 3)
       ACH_ID     protein_col  protein_intensity
0  ACH-000849  A0AV96 (RBM47)           0.358567
1  ACH-000441  A0AV96 (RBM47)          -1.112410
2  ACH-000248  A0AV96 (RBM47)           0.855575
3  ACH-000684  A0AV96 (RBM47)           0.061377
4  ACH-000856  A0AV96 (RBM47)           0.284258

In [7]:
df_4_long["uniprot_id"] = df_4_long["protein_col"].str.extract(r"^([A-Za-z0-9\-]+)")
df_4_long["hugo_symbol"] = df_4_long["protein_col"].str.extract(r"\((.+)\)")

df_4_long = df_4_long.drop(columns=["protein_col"])
print(df_4_long.head())

       ACH_ID  protein_intensity uniprot_id hugo_symbol
0  ACH-000849           0.358567     A0AV96       RBM47
1  ACH-000441          -1.112410     A0AV96       RBM47
2  ACH-000248           0.855575     A0AV96       RBM47
3  ACH-000684           0.061377     A0AV96       RBM47
4  ACH-000856           0.284258     A0AV96       RBM47

In [8]:
import re

folder = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\gene expression"
df_2 = pd.read_csv(folder + r"\2_DepMap_OmicsExpressionAllGenesTPMLogp1Profile.csv")

gene_cols = df_2.columns[1:]  

hugo_to_ensembl = {}
for col in gene_cols:
    match = re.match(r"^(.+) \((ENSG\d+)\)$", col)
    if match:
        hugo_to_ensembl[match.group(1)] = match.group(2)

print(f"mapping all: {len(hugo_to_ensembl)}")
print(list(hugo_to_ensembl.items())[:5])

mapping all: 53529
[('TSPAN6', 'ENSG00000000003'), ('TNMD', 'ENSG00000000005'), ('DPM1', 'ENSG00000000419'), ('SCYL3', 'ENSG00000000457'), ('C1orf112', 'ENSG00000000460')]

In [9]:
df_4_long["ensembl_id"] = df_4_long["hugo_symbol"].map(hugo_to_ensembl)

matched = df_4_long["ensembl_id"].notna().sum()
total = len(df_4_long)
print(f"match #: {matched} / {total} ({matched/total*100:.1f}%)")
print(df_4_long.head())

match #: 4659375 / 4709250 (98.9%)
       ACH_ID  protein_intensity uniprot_id hugo_symbol       ensembl_id
0  ACH-000849           0.358567     A0AV96       RBM47  ENSG00000163694
1  ACH-000441          -1.112410     A0AV96       RBM47  ENSG00000163694
2  ACH-000248           0.855575     A0AV96       RBM47  ENSG00000163694
3  ACH-000684           0.061377     A0AV96       RBM47  ENSG00000163694
4  ACH-000856           0.284258     A0AV96       RBM47  ENSG00000163694

In [10]:
df_4_long["is_detected"] = df_4_long["protein_intensity"].notna() & (df_4_long["protein_intensity"] != 0)

print(df_4_long["is_detected"].value_counts())

is_detected
True     3400546
False    1308704
Name: count, dtype: int64

In [11]:
df_4_long = df_4_long[["ACH_ID", "ensembl_id", "uniprot_id", "hugo_symbol", "protein_intensity", "is_detected"]]
print(df_4_long.head())
print(df_4_long.shape)

       ACH_ID       ensembl_id uniprot_id hugo_symbol  protein_intensity  \
0  ACH-000849  ENSG00000163694     A0AV96       RBM47           0.358567
1  ACH-000441  ENSG00000163694     A0AV96       RBM47          -1.112410
2  ACH-000248  ENSG00000163694     A0AV96       RBM47           0.855575
3  ACH-000684  ENSG00000163694     A0AV96       RBM47           0.061377
4  ACH-000856  ENSG00000163694     A0AV96       RBM47           0.284258

   is_detected
0         True
1         True
2         True
3         True
4         True
(4709250, 6)

In [12]:
df_4_long["z_score"] = df_4_long.groupby("ensembl_id")["protein_intensity"].transform(
    lambda x: (x - x.mean()) / x.std()
)

print(df_4_long.head(10))

       ACH_ID       ensembl_id uniprot_id hugo_symbol  protein_intensity  \
0  ACH-000849  ENSG00000163694     A0AV96       RBM47           0.358567
1  ACH-000441  ENSG00000163694     A0AV96       RBM47          -1.112410
2  ACH-000248  ENSG00000163694     A0AV96       RBM47           0.855575
3  ACH-000684  ENSG00000163694     A0AV96       RBM47           0.061377
4  ACH-000856  ENSG00000163694     A0AV96       RBM47           0.284258
5  ACH-000348  ENSG00000163694     A0AV96       RBM47          -0.485070
6  ACH-000062  ENSG00000163694     A0AV96       RBM47           0.092390
7  ACH-000650  ENSG00000163694     A0AV96       RBM47          -0.824035
8  ACH-000484  ENSG00000163694     A0AV96       RBM47           0.926286
9  ACH-000625  ENSG00000163694     A0AV96       RBM47           1.323508

   is_detected   z_score
0         True  0.263468
1         True -0.808447
2         True  0.625642
3         True  0.046903
4         True  0.209318
5         True -0.351298
6         True  0.069502
7         True -0.598306
8         True  0.677170
9         True  0.966630

In [13]:
df_4_long.head(100)

,ACH_ID,ensembl_id,uniprot_id,hugo_symbol,protein_intensity,is_detected,z_score
0,ACH-000849,ENSG00000163694,A0AV96,RBM47,0.358567,True,0.263468
1,ACH-000441,ENSG00000163694,A0AV96,RBM47,-1.112410,True,-0.808447
2,ACH-000248,ENSG00000163694,A0AV96,RBM47,0.855575,True,0.625642
3,ACH-000684,ENSG00000163694,A0AV96,RBM47,0.061377,True,0.046903
4,ACH-000856,ENSG00000163694,A0AV96,RBM47,0.284258,True,0.209318
...,...,...,...,...,...,...,...
95,ACH-000925,ENSG00000163694,A0AV96,RBM47,0.904805,True,0.661517
96,ACH-000532,ENSG00000163694,A0AV96,RBM47,0.935586,True,0.683947
97,ACH-000670,ENSG00000163694,A0AV96,RBM47,-2.637024,True,-1.919448
98,ACH-000724,ENSG00000163694,A0AV96,RBM47,-1.414719,True,-1.028742
99,ACH-000138,ENSG00000163694,A0AV96,RBM47,1.529975,True,1.117084

In [14]:
nom_folder = r"C:\Users\Pattanun\Downloads\AZ_project_data\data\nomenclature"
df_9 = pd.read_csv(nom_folder + r"\9_DepMap_sample_info.csv")

ach_to_cvcl = dict(zip(df_9["DepMap_ID"], df_9["RRID"]))

df_4_long["CVCL_ID"] = df_4_long["ACH_ID"].map(ach_to_cvcl)

# check match %
matched = df_4_long["CVCL_ID"].notna().sum()
total = len(df_4_long)
print(f"match #: {matched} / {total} ({matched/total*100:.1f}%)")

# manage column order (new)
df_4_long = df_4_long[["ACH_ID", "CVCL_ID", "ensembl_id", "uniprot_id", "hugo_symbol", "protein_intensity", "is_detected", "z_score"]]
print(df_4_long.head())

match #: 4709250 / 4709250 (100.0%)
       ACH_ID    CVCL_ID       ensembl_id uniprot_id hugo_symbol  \
0  ACH-000849  CVCL_0419  ENSG00000163694     A0AV96       RBM47
1  ACH-000441  CVCL_1692  ENSG00000163694     A0AV96       RBM47
2  ACH-000248  CVCL_1074  ENSG00000163694     A0AV96       RBM47
3  ACH-000684  CVCL_2983  ENSG00000163694     A0AV96       RBM47
4  ACH-000856  CVCL_1110  ENSG00000163694     A0AV96       RBM47

   protein_intensity  is_detected   z_score
0           0.358567         True  0.263468
1          -1.112410         True -0.808447
2           0.855575         True  0.625642
3           0.061377         True  0.046903
4           0.284258         True  0.209318

In [15]:
# Preview final fact_proteomics

df_4_long.head(100)

,ACH_ID,CVCL_ID,ensembl_id,uniprot_id,hugo_symbol,protein_intensity,is_detected,z_score
0,ACH-000849,CVCL_0419,ENSG00000163694,A0AV96,RBM47,0.358567,True,0.263468
1,ACH-000441,CVCL_1692,ENSG00000163694,A0AV96,RBM47,-1.112410,True,-0.808447
2,ACH-000248,CVCL_1074,ENSG00000163694,A0AV96,RBM47,0.855575,True,0.625642
3,ACH-000684,CVCL_2983,ENSG00000163694,A0AV96,RBM47,0.061377,True,0.046903
4,ACH-000856,CVCL_1110,ENSG00000163694,A0AV96,RBM47,0.284258,True,0.209318
...,...,...,...,...,...,...,...,...
95,ACH-000925,CVCL_1184,ENSG00000163694,A0AV96,RBM47,0.904805,True,0.661517
96,ACH-000532,CVCL_5078,ENSG00000163694,A0AV96,RBM47,0.935586,True,0.683947
97,ACH-000670,CVCL_1679,ENSG00000163694,A0AV96,RBM47,-2.637024,True,-1.919448
98,ACH-000724,CVCL_1292,ENSG00000163694,A0AV96,RBM47,-1.414719,True,-1.028742
99,ACH-000138,CVCL_1119,ENSG00000163694,A0AV96,RBM47,1.529975,True,1.117084

In [16]:
df_4_long.shape

(4709250, 8)

### Fact_expression

In [17]:
df_1 = pd.read_csv(folder + r"\1_4_hpa_rna_celline.tsv", sep="\t")
df_11 = pd.read_csv(nom_folder + r"\11_hpa_rna_celline_description.tsv", sep="\t")
df_9 = pd.read_csv(nom_folder + r"\9_DepMap_sample_info.csv")

print(df_1.head())
print(df_1.shape)

              Gene Gene name Cell line   TPM  pTPM  nTPM
0  ENSG00000000003    TSPAN6      143B  22.0  27.6  25.9
1  ENSG00000000003    TSPAN6     22Rv1   2.8   3.6   2.7
2  ENSG00000000003    TSPAN6  23132/87   6.2   7.5   7.5
3  ENSG00000000003    TSPAN6      253J  14.2  18.7  25.4
4  ENSG00000000003    TSPAN6   253J-BV  13.0  17.1  18.5
(24315372, 6)

In [18]:
df_1 = df_1.rename(columns={
    "Gene": "ensembl_id",
    "Gene name": "hugo_symbol",
    "Cell line": "Cell_line_name"
})

print(df_1.head())

        ensembl_id hugo_symbol Cell_line_name   TPM  pTPM  nTPM
0  ENSG00000000003      TSPAN6           143B  22.0  27.6  25.9
1  ENSG00000000003      TSPAN6          22Rv1   2.8   3.6   2.7
2  ENSG00000000003      TSPAN6       23132/87   6.2   7.5   7.5
3  ENSG00000000003      TSPAN6           253J  14.2  18.7  25.4
4  ENSG00000000003      TSPAN6        253J-BV  13.0  17.1  18.5

In [19]:
cellline_to_cvcl = dict(zip(df_11["Cell line"], df_11["Cellosaurus ID"]))

df_1["CVCL_ID"] = df_1["Cell_line_name"].map(cellline_to_cvcl)

matched = df_1["CVCL_ID"].notna().sum()
total = len(df_1)
print(f"match CVCL: {matched} / {total} ({matched/total*100:.1f}%)")

match CVCL: 24154076 / 24315372 (99.3%)

In [20]:
cvcl_to_ach = dict(zip(df_9["RRID"], df_9["DepMap_ID"]))

df_1["ACH_ID"] = df_1["CVCL_ID"].map(cvcl_to_ach)

matched_ach = df_1["ACH_ID"].notna().sum()
total = len(df_1)
print(f"match ACH: {matched_ach} / {total} ({matched_ach/total*100:.1f}%)")

print(df_1.head())

match ACH: 22420144 / 24315372 (92.2%)
        ensembl_id hugo_symbol Cell_line_name   TPM  pTPM  nTPM    CVCL_ID  \
0  ENSG00000000003      TSPAN6           143B  22.0  27.6  25.9  CVCL_2270
1  ENSG00000000003      TSPAN6          22Rv1   2.8   3.6   2.7  CVCL_1045
2  ENSG00000000003      TSPAN6       23132/87   6.2   7.5   7.5  CVCL_1046
3  ENSG00000000003      TSPAN6           253J  14.2  18.7  25.4  CVCL_7935
4  ENSG00000000003      TSPAN6        253J-BV  13.0  17.1  18.5  CVCL_7937

       ACH_ID
0  ACH-001001
1  ACH-000956
2  ACH-000948
3  ACH-000011
4  ACH-000026

In [21]:
import numpy as np

df_1["source"] = "hpa"
df_1["log2_tpm_plus1"] = np.log2(df_1["TPM"] + 1)
df_1["is_expressed"] = df_1["log2_tpm_plus1"] > 1

print(df_1.head())

        ensembl_id hugo_symbol Cell_line_name   TPM  pTPM  nTPM    CVCL_ID  \
0  ENSG00000000003      TSPAN6           143B  22.0  27.6  25.9  CVCL_2270
1  ENSG00000000003      TSPAN6          22Rv1   2.8   3.6   2.7  CVCL_1045
2  ENSG00000000003      TSPAN6       23132/87   6.2   7.5   7.5  CVCL_1046
3  ENSG00000000003      TSPAN6           253J  14.2  18.7  25.4  CVCL_7935
4  ENSG00000000003      TSPAN6        253J-BV  13.0  17.1  18.5  CVCL_7937

       ACH_ID source  log2_tpm_plus1  is_expressed
0  ACH-001001    hpa        4.523562          True
1  ACH-000956    hpa        1.925999          True
2  ACH-000948    hpa        2.847997          True
3  ACH-000011    hpa        3.925999          True
4  ACH-000026    hpa        3.807355          True

In [22]:
df_1_final = df_1[["ACH_ID", "CVCL_ID", "ensembl_id", "hugo_symbol", "source", "TPM", "pTPM", "nTPM", "log2_tpm_plus1", "is_expressed"]]
print(df_1_final.head())
print(df_1_final.shape)

       ACH_ID    CVCL_ID       ensembl_id hugo_symbol source   TPM  pTPM  \
0  ACH-001001  CVCL_2270  ENSG00000000003      TSPAN6    hpa  22.0  27.6
1  ACH-000956  CVCL_1045  ENSG00000000003      TSPAN6    hpa   2.8   3.6
2  ACH-000948  CVCL_1046  ENSG00000000003      TSPAN6    hpa   6.2   7.5
3  ACH-000011  CVCL_7935  ENSG00000000003      TSPAN6    hpa  14.2  18.7
4  ACH-000026  CVCL_7937  ENSG00000000003      TSPAN6    hpa  13.0  17.1

   nTPM  log2_tpm_plus1  is_expressed
0  25.9        4.523562          True
1   2.7        1.925999          True
2   7.5        2.847997          True
3  25.4        3.925999          True
4  18.5        3.807355          True
(24315372, 10)

In [23]:
import pandas as pd

df_2 = pd.read_csv(folder + r"\2_DepMap_OmicsExpressionAllGenesTPMLogp1Profile.csv")
df_8 = pd.read_csv(nom_folder + r"\8_DepMap_OmicsProfiles.csv")

print(df_2.shape)
print(df_2.iloc[:5, :5])

(1495, 53962)
  Unnamed: 0  TSPAN6 (ENSG00000000003)  TNMD (ENSG00000000005)  \
0  PR-AdBjpG                  4.331992                0.000000
1  PR-I2AzwG                  4.567424                0.584963
2  PR-5ekAAC                  3.150560                0.000000
3  PR-I21681                  5.085340                0.000000
4  PR-i9DRP1                  6.729417                0.000000

   DPM1 (ENSG00000000419)  SCYL3 (ENSG00000000457)
0                7.364660                 2.792855
1                7.106641                 2.543496
2                7.379118                 2.333424
3                7.154211                 2.545968
4                6.537917                 2.456806

In [24]:
df_2 = df_2.rename(columns={"Unnamed: 0": "PR_ID"})

# filter only rna profile
df8_rna = df_8[df_8["Datatype"] == "rna"]
pr_to_ach = dict(zip(df8_rna["ProfileID"], df8_rna["ModelID"]))

df_2["ACH_ID"] = df_2["PR_ID"].map(pr_to_ach)

matched = df_2["ACH_ID"].notna().sum()
total = len(df_2)
print(f"match ACH: {matched} / {total} ({matched/total*100:.1f}%)")
print(df_2[["PR_ID", "ACH_ID"]].head())

match ACH: 1495 / 1495 (100.0%)
       PR_ID      ACH_ID
0  PR-AdBjpG  ACH-001113
1  PR-I2AzwG  ACH-001289
2  PR-5ekAAC  ACH-001339
3  PR-I21681  ACH-001538
4  PR-i9DRP1  ACH-000242

In [25]:
import re

# parse column names first 
gene_cols = df_2.columns[2:]  # ข้าม PR_ID, ACH_ID

hugo_list = []
ensembl_list = []
valid_cols = []

for col in gene_cols:
    match = re.match(r"^(.+) \((ENSG\d+)\)$", col)
    if match:
        valid_cols.append(col)
        hugo_list.append(match.group(1))
        ensembl_list.append(match.group(2))

print(f"parse # {len(valid_cols)} genes from all {len(gene_cols)}")

parse # 53538 genes from all 53961

In [26]:
# only columns that can parse 
df_2_clean = df_2[["PR_ID", "ACH_ID"] + valid_cols]

# melt 
df_2_long = df_2_clean.melt(
    id_vars=["PR_ID", "ACH_ID"],
    var_name="gene_col",
    value_name="log2_tpm_plus1"
)

print(df_2_long.shape)
print(df_2_long.head())

(80039310, 4)
       PR_ID      ACH_ID                gene_col  log2_tpm_plus1
0  PR-AdBjpG  ACH-001113  TNMD (ENSG00000000005)        0.000000
1  PR-I2AzwG  ACH-001289  TNMD (ENSG00000000005)        0.584963
2  PR-5ekAAC  ACH-001339  TNMD (ENSG00000000005)        0.000000
3  PR-I21681  ACH-001538  TNMD (ENSG00000000005)        0.000000
4  PR-i9DRP1  ACH-000242  TNMD (ENSG00000000005)        0.000000

In [27]:
# create dict from gene_col from hugo_symbol, ensembl_id
col_to_hugo = dict(zip(valid_cols, hugo_list))
col_to_ensembl = dict(zip(valid_cols, ensembl_list))

df_2_long["hugo_symbol"] = df_2_long["gene_col"].map(col_to_hugo)
df_2_long["ensembl_id"] = df_2_long["gene_col"].map(col_to_ensembl)

df_2_long = df_2_long.drop(columns=["gene_col"])

print(df_2_long.head())
print(df_2_long.shape)

       PR_ID      ACH_ID  log2_tpm_plus1 hugo_symbol       ensembl_id
0  PR-AdBjpG  ACH-001113        0.000000        TNMD  ENSG00000000005
1  PR-I2AzwG  ACH-001289        0.584963        TNMD  ENSG00000000005
2  PR-5ekAAC  ACH-001339        0.000000        TNMD  ENSG00000000005
3  PR-I21681  ACH-001538        0.000000        TNMD  ENSG00000000005
4  PR-i9DRP1  ACH-000242        0.000000        TNMD  ENSG00000000005
(80039310, 5)

In [28]:
ach_to_cvcl = dict(zip(df_9["DepMap_ID"], df_9["RRID"]))

df_2_long["CVCL_ID"] = df_2_long["ACH_ID"].map(ach_to_cvcl)

# add columns
df_2_long["source"] = "depmap"
df_2_long["tpm"] = (2 ** df_2_long["log2_tpm_plus1"]) - 1
df_2_long["is_expressed"] = df_2_long["log2_tpm_plus1"] > 1

print(df_2_long.head())

       PR_ID      ACH_ID  log2_tpm_plus1 hugo_symbol       ensembl_id  \
0  PR-AdBjpG  ACH-001113        0.000000        TNMD  ENSG00000000005
1  PR-I2AzwG  ACH-001289        0.584963        TNMD  ENSG00000000005
2  PR-5ekAAC  ACH-001339        0.000000        TNMD  ENSG00000000005
3  PR-I21681  ACH-001538        0.000000        TNMD  ENSG00000000005
4  PR-i9DRP1  ACH-000242        0.000000        TNMD  ENSG00000000005

     CVCL_ID  source  tpm  is_expressed
0  CVCL_5480  depmap  0.0         False
1  CVCL_RS25  depmap  0.5         False
2  CVCL_2408  depmap  0.0         False
3  CVCL_M261  depmap  0.0         False
4  CVCL_0036  depmap  0.0         False

In [29]:
df_2_final = df_2_long[["ACH_ID", "CVCL_ID", "ensembl_id", "hugo_symbol", "PR_ID", "source", "tpm", "log2_tpm_plus1", "is_expressed"]]

print(df_2_final.head())
print(df_2_final.shape)

       ACH_ID    CVCL_ID       ensembl_id hugo_symbol      PR_ID  source  tpm  \
0  ACH-001113  CVCL_5480  ENSG00000000005        TNMD  PR-AdBjpG  depmap  0.0
1  ACH-001289  CVCL_RS25  ENSG00000000005        TNMD  PR-I2AzwG  depmap  0.5
2  ACH-001339  CVCL_2408  ENSG00000000005        TNMD  PR-5ekAAC  depmap  0.0
3  ACH-001538  CVCL_M261  ENSG00000000005        TNMD  PR-I21681  depmap  0.0
4  ACH-000242  CVCL_0036  ENSG00000000005        TNMD  PR-i9DRP1  depmap  0.0

   log2_tpm_plus1  is_expressed
0        0.000000         False
1        0.584963         False
2        0.000000         False
3        0.000000         False
4        0.000000         False
(80039310, 9)

In [30]:
df_3 = pd.read_csv(folder + r"\3_GEOexpression.txt", sep="\t")
df_10 = pd.read_csv(nom_folder + r"\10_GEOInfo.txt", sep="\t")

print(df_3.shape)
print(df_3.iloc[:5, :5])

(19914, 3268)
              Gene    GSM101610    GSM101615    GSM101616    GSM101667
0  ENSG00000000003    33.615700   553.249756   540.452209   599.431152
1  ENSG00000000005    40.925682    31.327406    33.934967    34.213123
2  ENSG00000000419  2182.281250  3419.430420  3514.540039  2295.817383
3  ENSG00000000457    58.934814    95.068222    94.900459    51.810070
4  ENSG00000000460   136.418900   257.929169   271.317230   162.090073

In [31]:
df_3_long = df_3.melt(
    id_vars=["Gene"],
    var_name="GSM_ID",
    value_name="tpm"
).rename(columns={"Gene": "ensembl_id"})

print(df_3_long.shape)
print(df_3_long.head())

(65059038, 3)
        ensembl_id     GSM_ID          tpm
0  ENSG00000000003  GSM101610    33.615700
1  ENSG00000000005  GSM101610    40.925682
2  ENSG00000000419  GSM101610  2182.281250
3  ENSG00000000457  GSM101610    58.934814
4  ENSG00000000460  GSM101610   136.418900

In [32]:
gsm_to_cvcl = dict(zip(df_10["Geo_accession"], df_10["Cellosaurus_ID"]))
cvcl_to_ach = dict(zip(df_9["RRID"], df_9["DepMap_ID"]))

df_3_long["CVCL_ID"] = df_3_long["GSM_ID"].map(gsm_to_cvcl)
df_3_long["ACH_ID"] = df_3_long["CVCL_ID"].map(cvcl_to_ach)

print(df_3_long.head())

        ensembl_id     GSM_ID          tpm    CVCL_ID      ACH_ID
0  ENSG00000000003  GSM101610    33.615700  CVCL_0131  ACH-000558
1  ENSG00000000005  GSM101610    40.925682  CVCL_0131  ACH-000558
2  ENSG00000000419  GSM101610  2182.281250  CVCL_0131  ACH-000558
3  ENSG00000000457  GSM101610    58.934814  CVCL_0131  ACH-000558
4  ENSG00000000460  GSM101610   136.418900  CVCL_0131  ACH-000558

In [33]:
df_3_long["source"] = "geo"
df_3_long["log2_tpm_plus1"] = np.log2(df_3_long["tpm"] + 1)
df_3_long["is_expressed"] = df_3_long["log2_tpm_plus1"] > 1

print(df_3_long.head())
print(df_3_long.shape)

        ensembl_id     GSM_ID          tpm    CVCL_ID      ACH_ID source  \
0  ENSG00000000003  GSM101610    33.615700  CVCL_0131  ACH-000558    geo
1  ENSG00000000005  GSM101610    40.925682  CVCL_0131  ACH-000558    geo
2  ENSG00000000419  GSM101610  2182.281250  CVCL_0131  ACH-000558    geo
3  ENSG00000000457  GSM101610    58.934814  CVCL_0131  ACH-000558    geo
4  ENSG00000000460  GSM101610   136.418900  CVCL_0131  ACH-000558    geo

   log2_tpm_plus1  is_expressed
0        5.113355          True
1        5.389762          True
2       11.092282          True
3        5.905322          True
4        7.102437          True
(65059038, 8)

In [34]:
df_3_final = df_3_long[["ACH_ID", "CVCL_ID", "ensembl_id", "GSM_ID", "source", "tpm", "log2_tpm_plus1", "is_expressed"]]
print(df_3_final.head())
print(df_3_final.shape)

       ACH_ID    CVCL_ID       ensembl_id     GSM_ID source          tpm  \
0  ACH-000558  CVCL_0131  ENSG00000000003  GSM101610    geo    33.615700
1  ACH-000558  CVCL_0131  ENSG00000000005  GSM101610    geo    40.925682
2  ACH-000558  CVCL_0131  ENSG00000000419  GSM101610    geo  2182.281250
3  ACH-000558  CVCL_0131  ENSG00000000457  GSM101610    geo    58.934814
4  ACH-000558  CVCL_0131  ENSG00000000460  GSM101610    geo   136.418900

   log2_tpm_plus1  is_expressed
0        5.113355          True
1        5.389762          True
2       11.092282          True
3        5.905322          True
4        7.102437          True
(65059038, 8)

combine all 3 datasets

In [35]:
print("HPA columns:", df_1_final.columns.tolist())
print("GEO columns:", df_3_final.columns.tolist())
print("DepMap columns:", df_2_final.columns.tolist())

HPA columns: ['ACH_ID', 'CVCL_ID', 'ensembl_id', 'hugo_symbol', 'source', 'TPM', 'pTPM', 'nTPM', 'log2_tpm_plus1', 'is_expressed']
GEO columns: ['ACH_ID', 'CVCL_ID', 'ensembl_id', 'GSM_ID', 'source', 'tpm', 'log2_tpm_plus1', 'is_expressed']
DepMap columns: ['ACH_ID', 'CVCL_ID', 'ensembl_id', 'hugo_symbol', 'PR_ID', 'source', 'tpm', 'log2_tpm_plus1', 'is_expressed']

In [36]:
df_1_final = df_1_final.rename(columns={"TPM": "tpm"})

print("HPA columns:", df_1_final.columns.tolist())

HPA columns: ['ACH_ID', 'CVCL_ID', 'ensembl_id', 'hugo_symbol', 'source', 'tpm', 'pTPM', 'nTPM', 'log2_tpm_plus1', 'is_expressed']